In [27]:
import re
import polars as pl
from glob import glob

# Using a `dict` to store tables by name.

On occasion, we will need to combine more than 2 files using some combination of `UNION` and `JOIN`.  In this lecture, we will show a clean approach to scaling up these operations up to any number of files.  In the process, we will

1. Use `list` comprehensions to process and `UNION` many similar files.
2. Use `dict` comprehensions to store and access many tables by name.

## Store in `dict` or `list`?

* Natural sequence/order? $\rightarrow$ `list`
    *  Example: Lakes data and years are a natural sequence
* Easier to refer by name? $\rightarrow$ `dict`
    * Baseball files have no order and easier to refer to by name

## The Basics of working with many files.

* Use `glob.glob` to find all files that match a pattern
* Convert all files to `pd.DataFrames`
* Store the `df` in a list or dictionary

### Extracting information from a `glob` search result.

**Options.**
1. Use string methods such as `split`, or
2. Use a regular expression.

In [30]:
all_baseball_csv = glob(
    './data/baseballdatabank*/**/*.csv',
    recursive=True
)

print(all_baseball_csv)

['./data\\baseballdatabank-2023.1\\contrib\\AwardsManagers.csv', './data\\baseballdatabank-2023.1\\contrib\\AwardsPlayers.csv', './data\\baseballdatabank-2023.1\\contrib\\AwardsShareManagers.csv', './data\\baseballdatabank-2023.1\\contrib\\AwardsSharePlayers.csv', './data\\baseballdatabank-2023.1\\contrib\\CollegePlaying.csv', './data\\baseballdatabank-2023.1\\contrib\\HallOfFame.csv', './data\\baseballdatabank-2023.1\\contrib\\Salaries.csv', './data\\baseballdatabank-2023.1\\contrib\\Schools.csv', './data\\baseballdatabank-2023.1\\core\\AllstarFull.csv', './data\\baseballdatabank-2023.1\\core\\Appearances.csv', './data\\baseballdatabank-2023.1\\core\\Batting.csv', './data\\baseballdatabank-2023.1\\core\\BattingPost.csv', './data\\baseballdatabank-2023.1\\core\\Fielding.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOF.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOFsplit.csv', './data\\baseballdatabank-2023.1\\core\\FieldingPost.csv', './data\\baseballdatabank-2023.1\\core\\HomeGames.csv', './data\\baseballdatabank-2023.1\\core\\Managers.csv', './data\\baseballdatabank-2023.1\\core\\ManagersHalf.csv', './data\\baseballdatabank-2023.1\\core\\Parks.csv', './data\\baseballdatabank-2023.1\\core\\People.csv', './data\\baseballdatabank-2023.1\\core\\Pitching.csv', './data\\baseballdatabank-2023.1\\core\\PitchingPost.csv', './data\\baseballdatabank-2023.1\\core\\SeriesPost.csv', './data\\baseballdatabank-2023.1\\core\\Teams.csv', './data\\baseballdatabank-2023.1\\core\\TeamsFranchises.csv', './data\\baseballdatabank-2023.1\\core\\TeamsHalf.csv', './data\\baseballdatabank-2023.1\\upstream\\Teams.csv']

#### Example 1 - Using the `str.split` method to extract a file name.

**Note.** The following cells are meant to show how the solution evolves.  In practice, this would all be proto-typed in a single cell.

In [37]:
# 1. Split on forward slash
[p.split('\\') for p in all_baseball_csv]

[['./data', 'baseballdatabank-2023.1', 'contrib', 'AwardsManagers.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'AwardsPlayers.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'AwardsShareManagers.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'AwardsSharePlayers.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'CollegePlaying.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'HallOfFame.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'Salaries.csv'],
 ['./data', 'baseballdatabank-2023.1', 'contrib', 'Schools.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'AllstarFull.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Appearances.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Batting.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'BattingPost.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Fielding.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'FieldingOF.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'FieldingOFsplit.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'FieldingPost.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'HomeGames.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Managers.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'ManagersHalf.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Parks.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'People.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Pitching.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'PitchingPost.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'SeriesPost.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'Teams.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'TeamsFranchises.csv'],
 ['./data', 'baseballdatabank-2023.1', 'core', 'TeamsHalf.csv'],
 ['./data', 'baseballdatabank-2023.1', 'upstream', 'Teams.csv']]

In [38]:
# 1. Split on forward slash
# 2. Get the last element 
[p.split('\\')[-1] for p in all_baseball_csv]

['AwardsManagers.csv',
 'AwardsPlayers.csv',
 'AwardsShareManagers.csv',
 'AwardsSharePlayers.csv',
 'CollegePlaying.csv',
 'HallOfFame.csv',
 'Salaries.csv',
 'Schools.csv',
 'AllstarFull.csv',
 'Appearances.csv',
 'Batting.csv',
 'BattingPost.csv',
 'Fielding.csv',
 'FieldingOF.csv',
 'FieldingOFsplit.csv',
 'FieldingPost.csv',
 'HomeGames.csv',
 'Managers.csv',
 'ManagersHalf.csv',
 'Parks.csv',
 'People.csv',
 'Pitching.csv',
 'PitchingPost.csv',
 'SeriesPost.csv',
 'Teams.csv',
 'TeamsFranchises.csv',
 'TeamsHalf.csv',
 'Teams.csv']

In [39]:
# 1. Split on forward slash
# 2. Get the last element 
# 3. Split off the file type 
[p.split('\\')[-1].split('.') for p in all_baseball_csv]

[['AwardsManagers', 'csv'],
 ['AwardsPlayers', 'csv'],
 ['AwardsShareManagers', 'csv'],
 ['AwardsSharePlayers', 'csv'],
 ['CollegePlaying', 'csv'],
 ['HallOfFame', 'csv'],
 ['Salaries', 'csv'],
 ['Schools', 'csv'],
 ['AllstarFull', 'csv'],
 ['Appearances', 'csv'],
 ['Batting', 'csv'],
 ['BattingPost', 'csv'],
 ['Fielding', 'csv'],
 ['FieldingOF', 'csv'],
 ['FieldingOFsplit', 'csv'],
 ['FieldingPost', 'csv'],
 ['HomeGames', 'csv'],
 ['Managers', 'csv'],
 ['ManagersHalf', 'csv'],
 ['Parks', 'csv'],
 ['People', 'csv'],
 ['Pitching', 'csv'],
 ['PitchingPost', 'csv'],
 ['SeriesPost', 'csv'],
 ['Teams', 'csv'],
 ['TeamsFranchises', 'csv'],
 ['TeamsHalf', 'csv'],
 ['Teams', 'csv']]

In [40]:
# 1. Split on forward slash
# 2. Get the last element 
# 3. Split off the file type 
# 4. Get the first enter (e.g. file name)
[p.split('\\')[-1].split('.')[0] for p in all_baseball_csv]

['AwardsManagers',
 'AwardsPlayers',
 'AwardsShareManagers',
 'AwardsSharePlayers',
 'CollegePlaying',
 'HallOfFame',
 'Salaries',
 'Schools',
 'AllstarFull',
 'Appearances',
 'Batting',
 'BattingPost',
 'Fielding',
 'FieldingOF',
 'FieldingOFsplit',
 'FieldingPost',
 'HomeGames',
 'Managers',
 'ManagersHalf',
 'Parks',
 'People',
 'Pitching',
 'PitchingPost',
 'SeriesPost',
 'Teams',
 'TeamsFranchises',
 'TeamsHalf',
 'Teams']

In [42]:
# 1. Split on forward slash
# 2. Get the last element 
# 3. Split off the file type 
# 4. Get the first enter (e.g. file name)
# 5. Refactor
get_file_name = lambda p: p.split('\\')[-1].split('.')[0]

[get_file_name(p) for p in all_baseball_csv]

['AwardsManagers',
 'AwardsPlayers',
 'AwardsShareManagers',
 'AwardsSharePlayers',
 'CollegePlaying',
 'HallOfFame',
 'Salaries',
 'Schools',
 'AllstarFull',
 'Appearances',
 'Batting',
 'BattingPost',
 'Fielding',
 'FieldingOF',
 'FieldingOFsplit',
 'FieldingPost',
 'HomeGames',
 'Managers',
 'ManagersHalf',
 'Parks',
 'People',
 'Pitching',
 'PitchingPost',
 'SeriesPost',
 'Teams',
 'TeamsFranchises',
 'TeamsHalf',
 'Teams']

#### Example 2 - Using a regular expression to capture the file name.

In [44]:
# 1. Start with an example path
file_name = re.compile(r'./data/baseballdatabank-2023.1/core/Managers.csv')
                       
[_match for p in all_baseball_csv if (_match := file_name.match(p))]

[]

In [45]:
# 1. Start with an example path
# 2. Make it match any file name

file_name = re.compile(r'./data/baseballdatabank-2023.1/core/[a-zA-Z]+.csv')

[_match for p in all_baseball_csv if (_match := file_name.match(p))]

[]

In [13]:
# 1. Start with an example path
# 2. Make it match any file name
# 3. Make it match any subfolder

file_name = re.compile(r'./data/baseballdatabank-2023.1/[a-z]+/[a-zA-Z]+.csv')

[_match for p in all_baseball_csv if (_match := file_name.match(p))]

[]

In [14]:
# 1. Start with an example path
# 2. Make it match any file name
# 3. Make it match any subfolder
# 4. Add a capture group and extract the data

file_name = re.compile(r'./data/baseballdatabank-2023.1/[a-z]+/([a-zA-Z]+).csv')

[_match.group(1) for p in all_baseball_csv if (_match := file_name.match(p))]

[]

In [15]:
# 1. Start with an example path
# 2. Make it match any file name
# 3. Make it match any subfolder
# 4. Add a capture group and extract the data
# 5. Refactor

file_name = re.compile(r'./data/baseballdatabank-2023.1/[a-z]+/([a-zA-Z]+).csv')

get_file_names = lambda paths: [_match.group(1) for p in paths if (_match := file_name.match(p))]

get_file_names(all_baseball_csv)

[]

### Dealing with Windows paths

* Windows uses backslash `\` instead of forward slash `/` to separate folders/files.
* Even on Windows, `glob` understands unix style paths that use `/` to separate files/folders.
* Since `\` is the escape character in Python, Windows paths will contain an escaped/literal backslash `\\`.
* The wild card parts of the pattern will return Windows style paths with `\\`

In [48]:
# Non-recursive search run on Windows
baseball_core_csv = glob('./data/baseballdatabank*/core/*csv')#, recursive=True)

baseball_core_csv

['./data\\baseballdatabank-2023.1\\core\\AllstarFull.csv',
 './data\\baseballdatabank-2023.1\\core\\Appearances.csv',
 './data\\baseballdatabank-2023.1\\core\\Batting.csv',
 './data\\baseballdatabank-2023.1\\core\\BattingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\Fielding.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingOF.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingOFsplit.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\HomeGames.csv',
 './data\\baseballdatabank-2023.1\\core\\Managers.csv',
 './data\\baseballdatabank-2023.1\\core\\ManagersHalf.csv',
 './data\\baseballdatabank-2023.1\\core\\Parks.csv',
 './data\\baseballdatabank-2023.1\\core\\People.csv',
 './data\\baseballdatabank-2023.1\\core\\Pitching.csv',
 './data\\baseballdatabank-2023.1\\core\\PitchingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\SeriesPost.csv',
 './data\\baseballdatabank-2023.1\\core\\Teams.csv',
 './data\\baseballdatabank-2023.1\\core\\TeamsFranchises.csv',
 './data\\baseballdatabank-2023.1\\core\\TeamsHalf.csv']

In [47]:
# Recursive search run on Windows
all_baseball_csv = glob('./data/baseballdatabank*/**/*.csv', recursive=True)

all_baseball_csv

['./data\\baseballdatabank-2023.1\\contrib\\AwardsManagers.csv',
 './data\\baseballdatabank-2023.1\\contrib\\AwardsPlayers.csv',
 './data\\baseballdatabank-2023.1\\contrib\\AwardsShareManagers.csv',
 './data\\baseballdatabank-2023.1\\contrib\\AwardsSharePlayers.csv',
 './data\\baseballdatabank-2023.1\\contrib\\CollegePlaying.csv',
 './data\\baseballdatabank-2023.1\\contrib\\HallOfFame.csv',
 './data\\baseballdatabank-2023.1\\contrib\\Salaries.csv',
 './data\\baseballdatabank-2023.1\\contrib\\Schools.csv',
 './data\\baseballdatabank-2023.1\\core\\AllstarFull.csv',
 './data\\baseballdatabank-2023.1\\core\\Appearances.csv',
 './data\\baseballdatabank-2023.1\\core\\Batting.csv',
 './data\\baseballdatabank-2023.1\\core\\BattingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\Fielding.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingOF.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingOFsplit.csv',
 './data\\baseballdatabank-2023.1\\core\\FieldingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\HomeGames.csv',
 './data\\baseballdatabank-2023.1\\core\\Managers.csv',
 './data\\baseballdatabank-2023.1\\core\\ManagersHalf.csv',
 './data\\baseballdatabank-2023.1\\core\\Parks.csv',
 './data\\baseballdatabank-2023.1\\core\\People.csv',
 './data\\baseballdatabank-2023.1\\core\\Pitching.csv',
 './data\\baseballdatabank-2023.1\\core\\PitchingPost.csv',
 './data\\baseballdatabank-2023.1\\core\\SeriesPost.csv',
 './data\\baseballdatabank-2023.1\\core\\Teams.csv',
 './data\\baseballdatabank-2023.1\\core\\TeamsFranchises.csv',
 './data\\baseballdatabank-2023.1\\core\\TeamsHalf.csv',
 './data\\baseballdatabank-2023.1\\upstream\\Teams.csv']

### Extracting information from Windows paths

On Windows, we need to switch `/` to `\\`

#### Example 1 - Split and get the file name in Windows

In [49]:
get_file_name = lambda p: p.split('\\')[-1].split('.')[0]

[get_file_name(p) for p in all_baseball_csv]

['AwardsManagers',
 'AwardsPlayers',
 'AwardsShareManagers',
 'AwardsSharePlayers',
 'CollegePlaying',
 'HallOfFame',
 'Salaries',
 'Schools',
 'AllstarFull',
 'Appearances',
 'Batting',
 'BattingPost',
 'Fielding',
 'FieldingOF',
 'FieldingOFsplit',
 'FieldingPost',
 'HomeGames',
 'Managers',
 'ManagersHalf',
 'Parks',
 'People',
 'Pitching',
 'PitchingPost',
 'SeriesPost',
 'Teams',
 'TeamsFranchises',
 'TeamsHalf',
 'Teams']

#### Example 2 - Using a regular expression to extract file name in Windows

In [50]:
file_name = re.compile(r'./data\\baseballdatabank-2023.1\\[a-z]+\\([a-zA-Z]+).csv')

get_file_names = lambda paths: [_match.group(1) for p in paths if (_match := file_name.match(p))]

get_file_names(all_baseball_csv)

['AwardsManagers',
 'AwardsPlayers',
 'AwardsShareManagers',
 'AwardsSharePlayers',
 'CollegePlaying',
 'HallOfFame',
 'Salaries',
 'Schools',
 'AllstarFull',
 'Appearances',
 'Batting',
 'BattingPost',
 'Fielding',
 'FieldingOF',
 'FieldingOFsplit',
 'FieldingPost',
 'HomeGames',
 'Managers',
 'ManagersHalf',
 'Parks',
 'People',
 'Pitching',
 'PitchingPost',
 'SeriesPost',
 'Teams',
 'TeamsFranchises',
 'TeamsHalf',
 'Teams']

## Storing tables by name in a `dict`

### Example 1 - Read all baseball database using `dict`

**Task:** Create a `dict` of tables for all tables in the Lahman database

#### Step 1 - Use `glob` to find paths for all CSV files

In [60]:
from glob import glob

files = glob('./data/baseballdatabank*/core/*.csv')
print(files)

['./data\\baseballdatabank-2023.1\\core\\AllstarFull.csv', './data\\baseballdatabank-2023.1\\core\\Appearances.csv', './data\\baseballdatabank-2023.1\\core\\Batting.csv', './data\\baseballdatabank-2023.1\\core\\BattingPost.csv', './data\\baseballdatabank-2023.1\\core\\Fielding.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOF.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOFsplit.csv', './data\\baseballdatabank-2023.1\\core\\FieldingPost.csv', './data\\baseballdatabank-2023.1\\core\\HomeGames.csv', './data\\baseballdatabank-2023.1\\core\\Managers.csv', './data\\baseballdatabank-2023.1\\core\\ManagersHalf.csv', './data\\baseballdatabank-2023.1\\core\\Parks.csv', './data\\baseballdatabank-2023.1\\core\\People.csv', './data\\baseballdatabank-2023.1\\core\\Pitching.csv', './data\\baseballdatabank-2023.1\\core\\PitchingPost.csv', './data\\baseballdatabank-2023.1\\core\\SeriesPost.csv', './data\\baseballdatabank-2023.1\\core\\Teams.csv', './data\\baseballdatabank-2023.1\\core\\TeamsFranchises.csv', './data\\baseballdatabank-2023.1\\core\\TeamsHalf.csv']

#### Step 2 - Make a function to extract the table name

In [61]:
import re
files = [p.replace('\\', '/') for p in files]

FILE_NAME_RE = re.compile(r'^\./data/baseballdatabank.*/core/([A-Za-z0-9_]+)\.csv$')
file_name = lambda p: FILE_NAME_RE.match(p).group(1) if FILE_NAME_RE.match(p) else None

print([file_name(p) for p in files])

['AllstarFull', 'Appearances', 'Batting', 'BattingPost', 'Fielding', 'FieldingOF', 'FieldingOFsplit', 'FieldingPost', 'HomeGames', 'Managers', 'ManagersHalf', 'Parks', 'People', 'Pitching', 'PitchingPost', 'SeriesPost', 'Teams', 'TeamsFranchises', 'TeamsHalf']

#### 4 - Read in the tables.

In [62]:
(baseball_db := 
 {file_name(p):pl.read_csv(p, infer_schema_length=10000) for p in files}
)

{'AllstarFull': shape: (5_516, 8)
 ┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
 │ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
 │ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
 │ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
 ╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
 │ gomezle01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ NYA    ┆ AL   ┆ 1   ┆ 1           │
 │ ferreri01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ BOS    ┆ AL   ┆ 1   ┆ 2           │
 │ gehrilo01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ NYA    ┆ AL   ┆ 1   ┆ 3           │
 │ gehrich01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ DET    ┆ AL   ┆ 1   ┆ 4           │
 │ dykesji01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ CHA    ┆ AL   ┆ 1   ┆ 5           │
 │ …         ┆ …      ┆ …       ┆ …            ┆ …      ┆ …    ┆ …   ┆ …           │
 │ rileyau01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ ATL    ┆ NL   ┆ 1   ┆ null        │
 │ schwaky01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
 │ sotoju01  ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ WAS    ┆ NL   ┆ 1   ┆ null        │
 │ swansda01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ ATL    ┆ NL   ┆ 1   ┆ null        │
 │ willide03 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ MIL    ┆ NL   ┆ 1   ┆ null        │
 └───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘,
 'Appearances': shape: (112_106, 21)
 ┌────────┬────────┬──────┬───────────┬───┬──────┬──────┬──────┬──────┐
 │ yearID ┆ teamID ┆ lgID ┆ playerID  ┆ … ┆ G_of ┆ G_dh ┆ G_ph ┆ G_pr │
 │ ---    ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ i64    ┆ str    ┆ str  ┆ str       ┆   ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
 ╞════════╪════════╪══════╪═══════════╪═══╪══════╪══════╪══════╪══════╡
 │ 1871   ┆ TRO    ┆ NA   ┆ abercda01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ RC1    ┆ NA   ┆ addybo01  ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ CL1    ┆ NA   ┆ allisar01 ┆ … ┆ 29   ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ WS3    ┆ NA   ┆ allisdo01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ RC1    ┆ NA   ┆ ansonca01 ┆ … ┆ 1    ┆ 0    ┆ 0    ┆ 0    │
 │ …      ┆ …      ┆ …    ┆ …         ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ 2022   ┆ CIN    ┆ NL   ┆ zeuchtj01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ PHI    ┆ NL   ┆ zimmebr01 ┆ … ┆ 9    ┆ 0    ┆ 0    ┆ 1    │
 │ 2022   ┆ TOR    ┆ AL   ┆ zimmebr01 ┆ … ┆ 90   ┆ 2    ┆ 8    ┆ 17   │
 │ 2022   ┆ BAL    ┆ AL   ┆ zimmebr02 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ TBA    ┆ AL   ┆ zuninmi01 ┆ … ┆ 0    ┆ 0    ┆ 2    ┆ 0    │
 └────────┴────────┴──────┴───────────┴───┴──────┴──────┴──────┴──────┘,
 'Batting': shape: (112_184, 22)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64  ┆ i64  ┆ str  ┆ i64  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ 1    │
 │ allisdo01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ ansonca01 ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ 5    ┆ 1    ┆ 0    ┆ 0    │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ 1    ┆ 0    ┆ 0    ┆ 0    │
 │ zimmebr02 ┆ 2022   ┆ 1     ┆ BAL    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ zuninmi01 ┆ 2022   ┆ 1     ┆ TBA    ┆ … ┆ 1    ┆ 0    ┆ 1    ┆ 2    │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'BattingPost': shape: (16_374, 22)
 ┌────────┬───────┬───────────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ yearID ┆ round ┆ playerID  ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
 │ ---    ┆ ---   ┆ ---       ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ i64    ┆ str   ┆ str       ┆ str    ┆   ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
 ╞════════╪═══════╪═══════════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ 1884   ┆ WS    ┆ becanbu01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ bradyst01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ carrocl01 ┆ PRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ dennyje01 ┆ PRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ esterdu01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …      ┆ …     ┆ …         ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ 2022   ┆ NLCS  ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLDS2 ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLWC1 ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLDS1 ┆ wrighky01 ┆ ATL    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLWC2 ┆ yepezju01 ┆ SLN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 └────────┴───────┴───────────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'Fielding': shape: (149_365, 18)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ WP   ┆ SB   ┆ CS   ┆ ZR   │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ str  ┆ i64  ┆ i64  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr02 ┆ 2022   ┆ 1     ┆ BAL    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zuninmi01 ┆ 2022   ┆ 1     ┆ TBA    ┆ … ┆ null ┆ 4    ┆ 15   ┆ null │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'FieldingOF': shape: (12_028, 6)
 ┌───────────┬────────┬───────┬─────┬─────┬─────┐
 │ playerID  ┆ yearID ┆ stint ┆ Glf ┆ Gcf ┆ Grf │
 │ ---       ┆ ---    ┆ ---   ┆ --- ┆ --- ┆ --- │
 │ str       ┆ i64    ┆ i64   ┆ i64 ┆ i64 ┆ i64 │
 ╞═══════════╪════════╪═══════╪═════╪═════╪═════╡
 │ allisar01 ┆ 1871   ┆ 1     ┆ 0   ┆ 29  ┆ 0   │
 │ ansonca01 ┆ 1871   ┆ 1     ┆ 1   ┆ 0   ┆ 0   │
 │ armstbo01 ┆ 1871   ┆ 1     ┆ 0   ┆ 11  ┆ 1   │
 │ barkeal01 ┆ 1871   ┆ 1     ┆ 1   ┆ 0   ┆ 0   │
 │ barrofr01 ┆ 1871   ┆ 1     ┆ 13  ┆ 0   ┆ 4   │
 │ …         ┆ …      ┆ …     ┆ …   ┆ …   ┆ …   │
 │ willite01 ┆ 1955   ┆ 1     ┆ 93  ┆ 0   ┆ 0   │
 │ wilsobi02 ┆ 1955   ┆ 1     ┆ 23  ┆ 57  ┆ 4   │
 │ woodlge01 ┆ 1955   ┆ 1     ┆ 26  ┆ 4   ┆ 25  │
 │ woodlge01 ┆ 1955   ┆ 2     ┆ 64  ┆ 0   ┆ 16  │
 │ zernigu01 ┆ 1955   ┆ 1     ┆ 103 ┆ 0   ┆ 0   │
 └───────────┴────────┴───────┴─────┴─────┴─────┘,
 'FieldingOFsplit': shape: (35_315, 18)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ WP   ┆ SB   ┆ CS   ┆ ZR   │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ str  ┆ str  ┆ str  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ aaronha01 ┆ 1954   ┆ 1     ┆ ML1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ aaronha01 ┆ 1954   ┆ 1     ┆ ML1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 1     ┆ PIT    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 1     ┆ PIT    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 2     ┆ BAL    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ youngja02 ┆ 2022   ┆ 1     ┆ CHN    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'FieldingPost': shape: (15_540, 17)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ TP  ┆ PB   ┆ SB   ┆ CS   │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64  ┆ str  ┆ str  │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪══════╪══════╪══════╡
 │ beaumgi01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ branski01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ clarkfr01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ colliji01 ┆ 1903   ┆ BOS    ┆ AL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ crigelo01 ┆ 1903   ┆ BOS    ┆ AL   ┆ … ┆ 0   ┆ 0    ┆ null ┆ null │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …    ┆ …    ┆ …    │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wrighky01 ┆ 2022   ┆ ATL    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ yepezju01 ┆ 2022   ┆ SLN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 └───────────┴────────┴────────┴──────┴───┴─────┴──────┴──────┴──────┘,
 'HomeGames': shape: (3_200, 9)
 ┌──────────┬────────────┬──────────┬──────────┬───┬────────────┬───────┬──────────┬────────────┐
 │ year.key ┆ league.key ┆ team.key ┆ park.key ┆ … ┆ span.last  ┆ games ┆ openings ┆ attendance │
 │ ---      ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---   ┆ ---      ┆ ---        │
 │ i64      ┆ str        ┆ str      ┆ str      ┆   ┆ str        ┆ i64   ┆ i64      ┆ i64        │
 ╞══════════╪════════════╪══════════╪══════════╪═══╪════════════╪═══════╪══════════╪════════════╡
 │ 1871     ┆ NA         ┆ BS1      ┆ BOS01    ┆ … ┆ 1871-10-07 ┆ 16    ┆ 16       ┆ 32600      │
 │ 1871     ┆ NA         ┆ BS1      ┆ NYC01    ┆ … ┆ 1871-05-27 ┆ 1     ┆ 1        ┆ 3000       │
 │ 1871     ┆ NA         ┆ CH1      ┆ CHI01    ┆ … ┆ 1871-09-29 ┆ 16    ┆ 15       ┆ 85500      │
 │ 1871     ┆ NA         ┆ CH1      ┆ NYC01    ┆ … ┆ 1871-10-30 ┆ 1     ┆ 1        ┆ 600        │
 │ 1871     ┆ NA         ┆ CL1      ┆ CIN01    ┆ … ┆ 1871-07-22 ┆ 2     ┆ 2        ┆ 2200       │
 │ …        ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …     ┆ …        ┆ …          │
 │ 2022     ┆ NL         ┆ SLN      ┆ STL10    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 3320551    │
 │ 2022     ┆ AL         ┆ TBA      ┆ STP01    ┆ … ┆ 2022-09-25 ┆ 81    ┆ 81       ┆ 1128127    │
 │ 2022     ┆ AL         ┆ TEX      ┆ ARL03    ┆ … ┆ 2022-10-05 ┆ 81    ┆ 81       ┆ 2011361    │
 │ 2022     ┆ AL         ┆ TOR      ┆ TOR02    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 2653830    │
 │ 2022     ┆ NL         ┆ WAS      ┆ WAS11    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 2026401    │
 └──────────┴────────────┴──────────┴──────────┴───┴────────────┴───────┴──────────┴────────────┘,
 'Managers': shape: (3_718, 10)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬─────┬──────┬─────────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ W   ┆ L   ┆ rank ┆ plyrMgr │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ --- ┆ ---  ┆ ---     │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64 ┆ i64  ┆ str     │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪═════╪══════╪═════════╡
 │ wrighha01 ┆ 1871   ┆ BS1    ┆ NA   ┆ … ┆ 20  ┆ 10  ┆ 3    ┆ Y       │
 │ woodji01  ┆ 1871   ┆ CH1    ┆ NA   ┆ … ┆ 19  ┆ 9   ┆ 2    ┆ Y       │
 │ paborch01 ┆ 1871   ┆ CL1    ┆ NA   ┆ … ┆ 10  ┆ 19  ┆ 8    ┆ Y       │
 │ lennobi01 ┆ 1871   ┆ FW1    ┆ NA   ┆ … ┆ 5   ┆ 9   ┆ 8    ┆ Y       │
 │ deaneha01 ┆ 1871   ┆ FW1    ┆ NA   ┆ … ┆ 2   ┆ 3   ┆ 8    ┆ Y       │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …   ┆ …    ┆ …       │
 │ sheltde99 ┆ 2022   ┆ PIT    ┆ NL   ┆ … ┆ 62  ┆ 100 ┆ 4    ┆ N       │
 │ melvibo01 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 89  ┆ 73  ┆ 2    ┆ N       │
 │ kaplega01 ┆ 2022   ┆ SFN    ┆ NL   ┆ … ┆ 81  ┆ 81  ┆ 3    ┆ N       │
 │ marmool99 ┆ 2022   ┆ SLN    ┆ NL   ┆ … ┆ 93  ┆ 69  ┆ 1    ┆ N       │
 │ martida01 ┆ 2022   ┆ WAS    ┆ NL   ┆ … ┆ 55  ┆ 107 ┆ 5    ┆ N       │
 └───────────┴────────┴────────┴──────┴───┴─────┴─────┴──────┴─────────┘,
 'ManagersHalf': shape: (93, 10)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬─────┬─────┬──────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ G   ┆ W   ┆ L   ┆ rank │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ --- ┆ --- ┆ ---  │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64 ┆ i64 ┆ i64  │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪═════╪═════╪══════╡
 │ hanlone01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 56  ┆ 17  ┆ 39  ┆ 12   │
 │ hanlone01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 77  ┆ 26  ┆ 46  ┆ 10   │
 │ vanhage01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 11  ┆ 1   ┆ 10  ┆ 12   │
 │ waltzjo99 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 8   ┆ 2   ┆ 6   ┆ 12   │
 │ wardjo01  ┆ 1892   ┆ BRO    ┆ NL   ┆ … ┆ 78  ┆ 51  ┆ 26  ┆ 2    │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …   ┆ …   ┆ …    │
 │ herzowh01 ┆ 1981   ┆ SLN    ┆ NL   ┆ … ┆ 52  ┆ 29  ┆ 23  ┆ 2    │
 │ zimmedo01 ┆ 1981   ┆ TEX    ┆ AL   ┆ … ┆ 55  ┆ 33  ┆ 22  ┆ 2    │
 │ zimmedo01 ┆ 1981   ┆ TEX    ┆ AL   ┆ … ┆ 50  ┆ 24  ┆ 26  ┆ 3    │
 │ mattibo01 ┆ 1981   ┆ TOR    ┆ AL   ┆ … ┆ 58  ┆ 16  ┆ 42  ┆ 7    │
 │ mattibo01 ┆ 1981   ┆ TOR    ┆ AL   ┆ … ┆ 48  ┆ 21  ┆ 27  ┆ 7    │
 └───────────┴────────┴────────┴──────┴───┴─────┴─────┴─────┴──────┘,
 'Parks': shape: (255, 6)
 ┌──────────┬──────────────────────────┬───────────────────────┬───────────────┬───────┬─────────┐
 │ park.key ┆ park.name                ┆ park.alias            ┆ city          ┆ state ┆ country │
 │ ---      ┆ ---                      ┆ ---                   ┆ ---           ┆ ---   ┆ ---     │
 │ str      ┆ str                      ┆ str                   ┆ str           ┆ str   ┆ str     │
 ╞══════════╪══════════════════════════╪═══════════════════════╪═══════════════╪═══════╪═════════╡
 │ ALB01    ┆ Riverside Park           ┆ null                  ┆ Albany        ┆ NY    ┆ US      │
 │ ALT01    ┆ Columbia Park            ┆ null                  ┆ Altoona       ┆ PA    ┆ US      │
 │ ANA01    ┆ Angel Stadium of Anaheim ┆ Edison Field; Anaheim ┆ Anaheim       ┆ CA    ┆ US      │
 │          ┆                          ┆ Stadium               ┆               ┆       ┆         │
 │ ARL01    ┆ Arlington Stadium        ┆ null                  ┆ Arlington     ┆ TX    ┆ US      │
 │ ARL02    ┆ Rangers Ballpark in      ┆ The Ballpark in       ┆ Arlington     ┆ TX    ┆ US      │
 │          ┆ Arlington                ┆ Arlington; Ame…       ┆               ┆       ┆         │
 │ …        ┆ …                        ┆ …                     ┆ …             ┆ …     ┆ …       │
 │ WIL02    ┆ BB&T Ballpark at Bowman  ┆ null                  ┆ Williamsport  ┆ PA    ┆ US      │
 │          ┆ Field                    ┆                       ┆               ┆       ┆         │
 │ WNY01    ┆ West New York Field Club ┆ null                  ┆ West New York ┆ NJ    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR01    ┆ Agricultural County Fair ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR02    ┆ Agricultural County Fair ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR03    ┆ Worcester Driving Park   ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Grounds                  ┆                       ┆               ┆       ┆         │
 └──────────┴──────────────────────────┴───────────────────────┴───────────────┴───────┴─────────┘,
 'People': shape: (20_676, 24)
 ┌───────────┬───────────┬────────────┬──────────┬───┬───────────┬───────────┬──────────┬───────────┐
 │ playerID  ┆ birthYear ┆ birthMonth ┆ birthDay ┆ … ┆ debut     ┆ finalGame ┆ retroID  ┆ bbrefID   │
 │ ---       ┆ ---       ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       │
 │ str       ┆ i64       ┆ i64        ┆ i64      ┆   ┆ str       ┆ str       ┆ str      ┆ str       │
 ╞═══════════╪═══════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
 │ aardsda01 ┆ 1981      ┆ 12         ┆ 27       ┆ … ┆ 2004-04-0 ┆ 2015-08-2 ┆ aardd001 ┆ aardsda01 │
 │           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
 │ aaronha01 ┆ 1934      ┆ 2          ┆ 5        ┆ … ┆ 1954-04-1 ┆ 1976-10-0 ┆ aaroh101 ┆ aaronha01 │
 │           ┆           ┆            ┆          ┆   ┆ 3         ┆ 3         ┆          ┆           │
 │ aaronto01 ┆ 1939      ┆ 8          ┆ 5        ┆ … ┆ 1962-04-1 ┆ 1971-09-2 ┆ aarot101 ┆ aaronto01 │
 │           ┆           ┆            ┆          ┆   ┆ 0         ┆ 6         ┆          ┆           │
 │ aasedo01  ┆ 1954      ┆ 9          ┆ 8        ┆ … ┆ 1977-07-2 ┆ 1990-10-0 ┆ aased001 ┆ aasedo01  │
 │           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
 │ abadan01  ┆ 1972      ┆ 8          ┆ 25       ┆ … ┆ 2001-09-1 ┆ 2006-04-1 ┆ abada001 ┆ abadan01  │
 │           ┆           ┆            ┆          ┆   ┆ 0         ┆ 3         ┆          ┆           │
 │ …         ┆ …         ┆ …          ┆ …        ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
 │ zupofr01  ┆ 1939      ┆ 8          ┆ 29       ┆ … ┆ 1957-07-0 ┆ 1961-05-0 ┆ zupof101 ┆ zupofr01  │
 │           ┆           ┆            ┆          ┆   ┆ 1         ┆ 9         ┆          ┆           │
 │ zuvelpa01 ┆ 1958      ┆ 10         ┆ 31       ┆ … ┆ 1982-09-0 ┆ 1991-05-0 ┆ zuvep001 ┆ zuvelpa01 │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 2         ┆          ┆           │
 │ zuverge01 ┆ 1924      ┆ 8          ┆ 20       ┆ … ┆ 1951-04-2 ┆ 1959-06-1 ┆ zuveg101 ┆ zuverge01 │
 │           ┆           ┆            ┆          ┆   ┆ 1         ┆ 5         ┆          ┆           │
 │ zwilldu01 ┆ 1888      ┆ 11         ┆ 2        ┆ … ┆ 1910-08-1 ┆ 1916-07-1 ┆ zwild101 ┆ zwilldu01 │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 2         ┆          ┆           │
 │ zychto01  ┆ 1990      ┆ 8          ┆ 7        ┆ … ┆ 2015-09-0 ┆ 2017-08-1 ┆ zycht001 ┆ zychto01  │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 9         ┆          ┆           │
 └───────────┴───────────┴────────────┴──────────┴───┴───────────┴───────────┴──────────┴───────────┘,
 'Pitching': shape: (50_402, 30)
 ┌───────────┬────────┬───────┬────────┬───┬─────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ R   ┆ SH   ┆ SF   ┆ GIDP │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64 ┆ str  ┆ str  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪═════╪══════╪══════╪══════╡
 │ bechtge01 ┆ 1871   ┆ 1     ┆ PH1    ┆ … ┆ 42  ┆ null ┆ null ┆ null │
 │ brainas01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ 292 ┆ null ┆ null ┆ null │
 │ fergubo01 ┆ 1871   ┆ 1     ┆ NY2    ┆ … ┆ 9   ┆ null ┆ null ┆ null │

### We can now access all the tables by name.

In [63]:
# Biggish output
baseball_db

{'AllstarFull': shape: (5_516, 8)
 ┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
 │ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
 │ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
 │ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
 ╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
 │ gomezle01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ NYA    ┆ AL   ┆ 1   ┆ 1           │
 │ ferreri01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ BOS    ┆ AL   ┆ 1   ┆ 2           │
 │ gehrilo01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ NYA    ┆ AL   ┆ 1   ┆ 3           │
 │ gehrich01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ DET    ┆ AL   ┆ 1   ┆ 4           │
 │ dykesji01 ┆ 1933   ┆ 0       ┆ ALS193307060 ┆ CHA    ┆ AL   ┆ 1   ┆ 5           │
 │ …         ┆ …      ┆ …       ┆ …            ┆ …      ┆ …    ┆ …   ┆ …           │
 │ rileyau01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ ATL    ┆ NL   ┆ 1   ┆ null        │
 │ schwaky01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
 │ sotoju01  ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ WAS    ┆ NL   ┆ 1   ┆ null        │
 │ swansda01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ ATL    ┆ NL   ┆ 1   ┆ null        │
 │ willide03 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ MIL    ┆ NL   ┆ 1   ┆ null        │
 └───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘,
 'Appearances': shape: (112_106, 21)
 ┌────────┬────────┬──────┬───────────┬───┬──────┬──────┬──────┬──────┐
 │ yearID ┆ teamID ┆ lgID ┆ playerID  ┆ … ┆ G_of ┆ G_dh ┆ G_ph ┆ G_pr │
 │ ---    ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ i64    ┆ str    ┆ str  ┆ str       ┆   ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
 ╞════════╪════════╪══════╪═══════════╪═══╪══════╪══════╪══════╪══════╡
 │ 1871   ┆ TRO    ┆ NA   ┆ abercda01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ RC1    ┆ NA   ┆ addybo01  ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ CL1    ┆ NA   ┆ allisar01 ┆ … ┆ 29   ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ WS3    ┆ NA   ┆ allisdo01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 1871   ┆ RC1    ┆ NA   ┆ ansonca01 ┆ … ┆ 1    ┆ 0    ┆ 0    ┆ 0    │
 │ …      ┆ …      ┆ …    ┆ …         ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ 2022   ┆ CIN    ┆ NL   ┆ zeuchtj01 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ PHI    ┆ NL   ┆ zimmebr01 ┆ … ┆ 9    ┆ 0    ┆ 0    ┆ 1    │
 │ 2022   ┆ TOR    ┆ AL   ┆ zimmebr01 ┆ … ┆ 90   ┆ 2    ┆ 8    ┆ 17   │
 │ 2022   ┆ BAL    ┆ AL   ┆ zimmebr02 ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ TBA    ┆ AL   ┆ zuninmi01 ┆ … ┆ 0    ┆ 0    ┆ 2    ┆ 0    │
 └────────┴────────┴──────┴───────────┴───┴──────┴──────┴──────┴──────┘,
 'Batting': shape: (112_184, 22)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64  ┆ i64  ┆ str  ┆ i64  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ 1    │
 │ allisdo01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ ansonca01 ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ 5    ┆ 1    ┆ 0    ┆ 0    │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ 1    ┆ 0    ┆ 0    ┆ 0    │
 │ zimmebr02 ┆ 2022   ┆ 1     ┆ BAL    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ zuninmi01 ┆ 2022   ┆ 1     ┆ TBA    ┆ … ┆ 1    ┆ 0    ┆ 1    ┆ 2    │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'BattingPost': shape: (16_374, 22)
 ┌────────┬───────┬───────────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ yearID ┆ round ┆ playerID  ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
 │ ---    ┆ ---   ┆ ---       ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ i64    ┆ str   ┆ str       ┆ str    ┆   ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
 ╞════════╪═══════╪═══════════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ 1884   ┆ WS    ┆ becanbu01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ bradyst01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ carrocl01 ┆ PRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ dennyje01 ┆ PRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ 1884   ┆ WS    ┆ esterdu01 ┆ NY4    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …      ┆ …     ┆ …         ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ 2022   ┆ NLCS  ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLDS2 ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLWC1 ┆ wilsost02 ┆ SDN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLDS1 ┆ wrighky01 ┆ ATL    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 │ 2022   ┆ NLWC2 ┆ yepezju01 ┆ SLN    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
 └────────┴───────┴───────────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'Fielding': shape: (149_365, 18)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ WP   ┆ SB   ┆ CS   ┆ ZR   │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ str  ┆ i64  ┆ i64  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr02 ┆ 2022   ┆ 1     ┆ BAL    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zuninmi01 ┆ 2022   ┆ 1     ┆ TBA    ┆ … ┆ null ┆ 4    ┆ 15   ┆ null │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'FieldingOF': shape: (12_028, 6)
 ┌───────────┬────────┬───────┬─────┬─────┬─────┐
 │ playerID  ┆ yearID ┆ stint ┆ Glf ┆ Gcf ┆ Grf │
 │ ---       ┆ ---    ┆ ---   ┆ --- ┆ --- ┆ --- │
 │ str       ┆ i64    ┆ i64   ┆ i64 ┆ i64 ┆ i64 │
 ╞═══════════╪════════╪═══════╪═════╪═════╪═════╡
 │ allisar01 ┆ 1871   ┆ 1     ┆ 0   ┆ 29  ┆ 0   │
 │ ansonca01 ┆ 1871   ┆ 1     ┆ 1   ┆ 0   ┆ 0   │
 │ armstbo01 ┆ 1871   ┆ 1     ┆ 0   ┆ 11  ┆ 1   │
 │ barkeal01 ┆ 1871   ┆ 1     ┆ 1   ┆ 0   ┆ 0   │
 │ barrofr01 ┆ 1871   ┆ 1     ┆ 13  ┆ 0   ┆ 4   │
 │ …         ┆ …      ┆ …     ┆ …   ┆ …   ┆ …   │
 │ willite01 ┆ 1955   ┆ 1     ┆ 93  ┆ 0   ┆ 0   │
 │ wilsobi02 ┆ 1955   ┆ 1     ┆ 23  ┆ 57  ┆ 4   │
 │ woodlge01 ┆ 1955   ┆ 1     ┆ 26  ┆ 4   ┆ 25  │
 │ woodlge01 ┆ 1955   ┆ 2     ┆ 64  ┆ 0   ┆ 16  │
 │ zernigu01 ┆ 1955   ┆ 1     ┆ 103 ┆ 0   ┆ 0   │
 └───────────┴────────┴───────┴─────┴─────┴─────┘,
 'FieldingOFsplit': shape: (35_315, 18)
 ┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ WP   ┆ SB   ┆ CS   ┆ ZR   │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ str  ┆ str  ┆ str  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
 │ aaronha01 ┆ 1954   ┆ 1     ┆ ML1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ aaronha01 ┆ 1954   ┆ 1     ┆ ML1    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 1     ┆ PIT    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 1     ┆ PIT    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ abramca01 ┆ 1954   ┆ 2     ┆ BAL    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
 │ youngja02 ┆ 2022   ┆ 1     ┆ CHN    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ null ┆ null ┆ null ┆ null │
 │ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ null ┆ null ┆ null ┆ null │
 └───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘,
 'FieldingPost': shape: (15_540, 17)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ TP  ┆ PB   ┆ SB   ┆ CS   │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64  ┆ str  ┆ str  │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪══════╪══════╪══════╡
 │ beaumgi01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ branski01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ clarkfr01 ┆ 1903   ┆ PIT    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ colliji01 ┆ 1903   ┆ BOS    ┆ AL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ crigelo01 ┆ 1903   ┆ BOS    ┆ AL   ┆ … ┆ 0   ┆ 0    ┆ null ┆ null │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …    ┆ …    ┆ …    │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wilsost02 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ wrighky01 ┆ 2022   ┆ ATL    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 │ yepezju01 ┆ 2022   ┆ SLN    ┆ NL   ┆ … ┆ 0   ┆ null ┆ null ┆ null │
 └───────────┴────────┴────────┴──────┴───┴─────┴──────┴──────┴──────┘,
 'HomeGames': shape: (3_200, 9)
 ┌──────────┬────────────┬──────────┬──────────┬───┬────────────┬───────┬──────────┬────────────┐
 │ year.key ┆ league.key ┆ team.key ┆ park.key ┆ … ┆ span.last  ┆ games ┆ openings ┆ attendance │
 │ ---      ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---   ┆ ---      ┆ ---        │
 │ i64      ┆ str        ┆ str      ┆ str      ┆   ┆ str        ┆ i64   ┆ i64      ┆ i64        │
 ╞══════════╪════════════╪══════════╪══════════╪═══╪════════════╪═══════╪══════════╪════════════╡
 │ 1871     ┆ NA         ┆ BS1      ┆ BOS01    ┆ … ┆ 1871-10-07 ┆ 16    ┆ 16       ┆ 32600      │
 │ 1871     ┆ NA         ┆ BS1      ┆ NYC01    ┆ … ┆ 1871-05-27 ┆ 1     ┆ 1        ┆ 3000       │
 │ 1871     ┆ NA         ┆ CH1      ┆ CHI01    ┆ … ┆ 1871-09-29 ┆ 16    ┆ 15       ┆ 85500      │
 │ 1871     ┆ NA         ┆ CH1      ┆ NYC01    ┆ … ┆ 1871-10-30 ┆ 1     ┆ 1        ┆ 600        │
 │ 1871     ┆ NA         ┆ CL1      ┆ CIN01    ┆ … ┆ 1871-07-22 ┆ 2     ┆ 2        ┆ 2200       │
 │ …        ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …     ┆ …        ┆ …          │
 │ 2022     ┆ NL         ┆ SLN      ┆ STL10    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 3320551    │
 │ 2022     ┆ AL         ┆ TBA      ┆ STP01    ┆ … ┆ 2022-09-25 ┆ 81    ┆ 81       ┆ 1128127    │
 │ 2022     ┆ AL         ┆ TEX      ┆ ARL03    ┆ … ┆ 2022-10-05 ┆ 81    ┆ 81       ┆ 2011361    │
 │ 2022     ┆ AL         ┆ TOR      ┆ TOR02    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 2653830    │
 │ 2022     ┆ NL         ┆ WAS      ┆ WAS11    ┆ … ┆ 2022-10-02 ┆ 81    ┆ 81       ┆ 2026401    │
 └──────────┴────────────┴──────────┴──────────┴───┴────────────┴───────┴──────────┴────────────┘,
 'Managers': shape: (3_718, 10)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬─────┬──────┬─────────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ W   ┆ L   ┆ rank ┆ plyrMgr │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ --- ┆ ---  ┆ ---     │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64 ┆ i64  ┆ str     │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪═════╪══════╪═════════╡
 │ wrighha01 ┆ 1871   ┆ BS1    ┆ NA   ┆ … ┆ 20  ┆ 10  ┆ 3    ┆ Y       │
 │ woodji01  ┆ 1871   ┆ CH1    ┆ NA   ┆ … ┆ 19  ┆ 9   ┆ 2    ┆ Y       │
 │ paborch01 ┆ 1871   ┆ CL1    ┆ NA   ┆ … ┆ 10  ┆ 19  ┆ 8    ┆ Y       │
 │ lennobi01 ┆ 1871   ┆ FW1    ┆ NA   ┆ … ┆ 5   ┆ 9   ┆ 8    ┆ Y       │
 │ deaneha01 ┆ 1871   ┆ FW1    ┆ NA   ┆ … ┆ 2   ┆ 3   ┆ 8    ┆ Y       │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …   ┆ …    ┆ …       │
 │ sheltde99 ┆ 2022   ┆ PIT    ┆ NL   ┆ … ┆ 62  ┆ 100 ┆ 4    ┆ N       │
 │ melvibo01 ┆ 2022   ┆ SDN    ┆ NL   ┆ … ┆ 89  ┆ 73  ┆ 2    ┆ N       │
 │ kaplega01 ┆ 2022   ┆ SFN    ┆ NL   ┆ … ┆ 81  ┆ 81  ┆ 3    ┆ N       │
 │ marmool99 ┆ 2022   ┆ SLN    ┆ NL   ┆ … ┆ 93  ┆ 69  ┆ 1    ┆ N       │
 │ martida01 ┆ 2022   ┆ WAS    ┆ NL   ┆ … ┆ 55  ┆ 107 ┆ 5    ┆ N       │
 └───────────┴────────┴────────┴──────┴───┴─────┴─────┴──────┴─────────┘,
 'ManagersHalf': shape: (93, 10)
 ┌───────────┬────────┬────────┬──────┬───┬─────┬─────┬─────┬──────┐
 │ playerID  ┆ yearID ┆ teamID ┆ lgID ┆ … ┆ G   ┆ W   ┆ L   ┆ rank │
 │ ---       ┆ ---    ┆ ---    ┆ ---  ┆   ┆ --- ┆ --- ┆ --- ┆ ---  │
 │ str       ┆ i64    ┆ str    ┆ str  ┆   ┆ i64 ┆ i64 ┆ i64 ┆ i64  │
 ╞═══════════╪════════╪════════╪══════╪═══╪═════╪═════╪═════╪══════╡
 │ hanlone01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 56  ┆ 17  ┆ 39  ┆ 12   │
 │ hanlone01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 77  ┆ 26  ┆ 46  ┆ 10   │
 │ vanhage01 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 11  ┆ 1   ┆ 10  ┆ 12   │
 │ waltzjo99 ┆ 1892   ┆ BLN    ┆ NL   ┆ … ┆ 8   ┆ 2   ┆ 6   ┆ 12   │
 │ wardjo01  ┆ 1892   ┆ BRO    ┆ NL   ┆ … ┆ 78  ┆ 51  ┆ 26  ┆ 2    │
 │ …         ┆ …      ┆ …      ┆ …    ┆ … ┆ …   ┆ …   ┆ …   ┆ …    │
 │ herzowh01 ┆ 1981   ┆ SLN    ┆ NL   ┆ … ┆ 52  ┆ 29  ┆ 23  ┆ 2    │
 │ zimmedo01 ┆ 1981   ┆ TEX    ┆ AL   ┆ … ┆ 55  ┆ 33  ┆ 22  ┆ 2    │
 │ zimmedo01 ┆ 1981   ┆ TEX    ┆ AL   ┆ … ┆ 50  ┆ 24  ┆ 26  ┆ 3    │
 │ mattibo01 ┆ 1981   ┆ TOR    ┆ AL   ┆ … ┆ 58  ┆ 16  ┆ 42  ┆ 7    │
 │ mattibo01 ┆ 1981   ┆ TOR    ┆ AL   ┆ … ┆ 48  ┆ 21  ┆ 27  ┆ 7    │
 └───────────┴────────┴────────┴──────┴───┴─────┴─────┴─────┴──────┘,
 'Parks': shape: (255, 6)
 ┌──────────┬──────────────────────────┬───────────────────────┬───────────────┬───────┬─────────┐
 │ park.key ┆ park.name                ┆ park.alias            ┆ city          ┆ state ┆ country │
 │ ---      ┆ ---                      ┆ ---                   ┆ ---           ┆ ---   ┆ ---     │
 │ str      ┆ str                      ┆ str                   ┆ str           ┆ str   ┆ str     │
 ╞══════════╪══════════════════════════╪═══════════════════════╪═══════════════╪═══════╪═════════╡
 │ ALB01    ┆ Riverside Park           ┆ null                  ┆ Albany        ┆ NY    ┆ US      │
 │ ALT01    ┆ Columbia Park            ┆ null                  ┆ Altoona       ┆ PA    ┆ US      │
 │ ANA01    ┆ Angel Stadium of Anaheim ┆ Edison Field; Anaheim ┆ Anaheim       ┆ CA    ┆ US      │
 │          ┆                          ┆ Stadium               ┆               ┆       ┆         │
 │ ARL01    ┆ Arlington Stadium        ┆ null                  ┆ Arlington     ┆ TX    ┆ US      │
 │ ARL02    ┆ Rangers Ballpark in      ┆ The Ballpark in       ┆ Arlington     ┆ TX    ┆ US      │
 │          ┆ Arlington                ┆ Arlington; Ame…       ┆               ┆       ┆         │
 │ …        ┆ …                        ┆ …                     ┆ …             ┆ …     ┆ …       │
 │ WIL02    ┆ BB&T Ballpark at Bowman  ┆ null                  ┆ Williamsport  ┆ PA    ┆ US      │
 │          ┆ Field                    ┆                       ┆               ┆       ┆         │
 │ WNY01    ┆ West New York Field Club ┆ null                  ┆ West New York ┆ NJ    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR01    ┆ Agricultural County Fair ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR02    ┆ Agricultural County Fair ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Groun…                   ┆                       ┆               ┆       ┆         │
 │ WOR03    ┆ Worcester Driving Park   ┆ null                  ┆ Worcester     ┆ MA    ┆ US      │
 │          ┆ Grounds                  ┆                       ┆               ┆       ┆         │
 └──────────┴──────────────────────────┴───────────────────────┴───────────────┴───────┴─────────┘,
 'People': shape: (20_676, 24)
 ┌───────────┬───────────┬────────────┬──────────┬───┬───────────┬───────────┬──────────┬───────────┐
 │ playerID  ┆ birthYear ┆ birthMonth ┆ birthDay ┆ … ┆ debut     ┆ finalGame ┆ retroID  ┆ bbrefID   │
 │ ---       ┆ ---       ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       │
 │ str       ┆ i64       ┆ i64        ┆ i64      ┆   ┆ str       ┆ str       ┆ str      ┆ str       │
 ╞═══════════╪═══════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
 │ aardsda01 ┆ 1981      ┆ 12         ┆ 27       ┆ … ┆ 2004-04-0 ┆ 2015-08-2 ┆ aardd001 ┆ aardsda01 │
 │           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
 │ aaronha01 ┆ 1934      ┆ 2          ┆ 5        ┆ … ┆ 1954-04-1 ┆ 1976-10-0 ┆ aaroh101 ┆ aaronha01 │
 │           ┆           ┆            ┆          ┆   ┆ 3         ┆ 3         ┆          ┆           │
 │ aaronto01 ┆ 1939      ┆ 8          ┆ 5        ┆ … ┆ 1962-04-1 ┆ 1971-09-2 ┆ aarot101 ┆ aaronto01 │
 │           ┆           ┆            ┆          ┆   ┆ 0         ┆ 6         ┆          ┆           │
 │ aasedo01  ┆ 1954      ┆ 9          ┆ 8        ┆ … ┆ 1977-07-2 ┆ 1990-10-0 ┆ aased001 ┆ aasedo01  │
 │           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
 │ abadan01  ┆ 1972      ┆ 8          ┆ 25       ┆ … ┆ 2001-09-1 ┆ 2006-04-1 ┆ abada001 ┆ abadan01  │
 │           ┆           ┆            ┆          ┆   ┆ 0         ┆ 3         ┆          ┆           │
 │ …         ┆ …         ┆ …          ┆ …        ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
 │ zupofr01  ┆ 1939      ┆ 8          ┆ 29       ┆ … ┆ 1957-07-0 ┆ 1961-05-0 ┆ zupof101 ┆ zupofr01  │
 │           ┆           ┆            ┆          ┆   ┆ 1         ┆ 9         ┆          ┆           │
 │ zuvelpa01 ┆ 1958      ┆ 10         ┆ 31       ┆ … ┆ 1982-09-0 ┆ 1991-05-0 ┆ zuvep001 ┆ zuvelpa01 │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 2         ┆          ┆           │
 │ zuverge01 ┆ 1924      ┆ 8          ┆ 20       ┆ … ┆ 1951-04-2 ┆ 1959-06-1 ┆ zuveg101 ┆ zuverge01 │
 │           ┆           ┆            ┆          ┆   ┆ 1         ┆ 5         ┆          ┆           │
 │ zwilldu01 ┆ 1888      ┆ 11         ┆ 2        ┆ … ┆ 1910-08-1 ┆ 1916-07-1 ┆ zwild101 ┆ zwilldu01 │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 2         ┆          ┆           │
 │ zychto01  ┆ 1990      ┆ 8          ┆ 7        ┆ … ┆ 2015-09-0 ┆ 2017-08-1 ┆ zycht001 ┆ zychto01  │
 │           ┆           ┆            ┆          ┆   ┆ 4         ┆ 9         ┆          ┆           │
 └───────────┴───────────┴────────────┴──────────┴───┴───────────┴───────────┴──────────┴───────────┘,
 'Pitching': shape: (50_402, 30)
 ┌───────────┬────────┬───────┬────────┬───┬─────┬──────┬──────┬──────┐
 │ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ R   ┆ SH   ┆ SF   ┆ GIDP │
 │ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---  │
 │ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64 ┆ str  ┆ str  ┆ str  │
 ╞═══════════╪════════╪═══════╪════════╪═══╪═════╪══════╪══════╪══════╡
 │ bechtge01 ┆ 1871   ┆ 1     ┆ PH1    ┆ … ┆ 42  ┆ null ┆ null ┆ null │
 │ brainas01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ 292 ┆ null ┆ null ┆ null │
 │ fergubo01 ┆ 1871   ┆ 1     ┆ NY2    ┆ … ┆ 9   ┆ null ┆ null ┆ null │

In [64]:
baseball_db['Teams']

shape: (3_015, 48)
┌────────┬──────┬────────┬──────────┬───┬─────┬──────────┬────────────────┬─────────────┐
│ yearID ┆ lgID ┆ teamID ┆ franchID ┆ … ┆ PPF ┆ teamIDBR ┆ teamIDlahman45 ┆ teamIDretro │
│ ---    ┆ ---  ┆ ---    ┆ ---      ┆   ┆ --- ┆ ---      ┆ ---            ┆ ---         │
│ i64    ┆ str  ┆ str    ┆ str      ┆   ┆ i64 ┆ str      ┆ str            ┆ str         │
╞════════╪══════╪════════╪══════════╪═══╪═════╪══════════╪════════════════╪═════════════╡
│ 1871   ┆ NA   ┆ BS1    ┆ BNA      ┆ … ┆ 98  ┆ BOS      ┆ BS1            ┆ BS1         │
│ 1871   ┆ NA   ┆ CH1    ┆ CNA      ┆ … ┆ 102 ┆ CHI      ┆ CH1            ┆ CH1         │
│ 1871   ┆ NA   ┆ CL1    ┆ CFC      ┆ … ┆ 100 ┆ CLE      ┆ CL1            ┆ CL1         │
│ 1871   ┆ NA   ┆ FW1    ┆ KEK      ┆ … ┆ 107 ┆ KEK      ┆ FW1            ┆ FW1         │
│ 1871   ┆ NA   ┆ NY2    ┆ NNA      ┆ … ┆ 88  ┆ NYU      ┆ NY2            ┆ NY2         │
│ …      ┆ …    ┆ …      ┆ …        ┆ … ┆ …   ┆ …        ┆ …              ┆ …           │
│ 2022   ┆ NL   ┆ SLN    ┆ STL      ┆ … ┆ 94  ┆ STL      ┆ SLN            ┆ SLN         │
│ 2022   ┆ AL   ┆ TBA    ┆ TBD      ┆ … ┆ 93  ┆ TBR      ┆ TBA            ┆ TBA         │
│ 2022   ┆ AL   ┆ TEX    ┆ TEX      ┆ … ┆ 101 ┆ TEX      ┆ TEX            ┆ TEX         │
│ 2022   ┆ AL   ┆ TOR    ┆ TOR      ┆ … ┆ 100 ┆ TOR      ┆ TOR            ┆ TOR         │
│ 2022   ┆ NL   ┆ WAS    ┆ WSN      ┆ … ┆ 96  ┆ WSN      ┆ MON            ┆ WAS         │
└────────┴──────┴────────┴──────────┴───┴─────┴──────────┴────────────────┴─────────────┘

In [65]:
baseball_db['Batting']

shape: (112_184, 22)
┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
│ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
│ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64  ┆ i64  ┆ str  ┆ i64  │
╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
│ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ 1    │
│ allisdo01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ ansonca01 ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ zimmebr01 ┆ 2022   ┆ 1     ┆ TOR    ┆ … ┆ 5    ┆ 1    ┆ 0    ┆ 0    │
│ zimmebr01 ┆ 2022   ┆ 2     ┆ PHI    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ zimmebr01 ┆ 2022   ┆ 3     ┆ TOR    ┆ … ┆ 1    ┆ 0    ┆ 0    ┆ 0    │
│ zimmebr02 ┆ 2022   ┆ 1     ┆ BAL    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ zuninmi01 ┆ 2022   ┆ 1     ┆ TBA    ┆ … ┆ 1    ┆ 0    ┆ 1    ┆ 2    │
└───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘

## Example 2 - Reading and joining the baseball database using `dict`

**Task:** Collect the number of total hits for each batters in the 2010 season join on their first and last name.

In the second example, we will store the data frames in a `dict`, which will make it easier to join the files by ne

#### Step 1 - Get the files names

* Only need the `Batting.csv` and `People.csv`.  
* Narrow with a RegEx

In [67]:

from glob import glob

files = glob('./data/baseballdatabank*/core/*.csv')
print(files)

['./data\\baseballdatabank-2023.1\\core\\AllstarFull.csv', './data\\baseballdatabank-2023.1\\core\\Appearances.csv', './data\\baseballdatabank-2023.1\\core\\Batting.csv', './data\\baseballdatabank-2023.1\\core\\BattingPost.csv', './data\\baseballdatabank-2023.1\\core\\Fielding.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOF.csv', './data\\baseballdatabank-2023.1\\core\\FieldingOFsplit.csv', './data\\baseballdatabank-2023.1\\core\\FieldingPost.csv', './data\\baseballdatabank-2023.1\\core\\HomeGames.csv', './data\\baseballdatabank-2023.1\\core\\Managers.csv', './data\\baseballdatabank-2023.1\\core\\ManagersHalf.csv', './data\\baseballdatabank-2023.1\\core\\Parks.csv', './data\\baseballdatabank-2023.1\\core\\People.csv', './data\\baseballdatabank-2023.1\\core\\Pitching.csv', './data\\baseballdatabank-2023.1\\core\\PitchingPost.csv', './data\\baseballdatabank-2023.1\\core\\SeriesPost.csv', './data\\baseballdatabank-2023.1\\core\\Teams.csv', './data\\baseballdatabank-2023.1\\core\\TeamsFranchises.csv', './data\\baseballdatabank-2023.1\\core\\TeamsHalf.csv']

#### Step 2 - Make helper functions to get the name from path

In [75]:
import re

# normalize paths to forward slashes
files = [p.replace('\\', '/') for p in files]

FILE_NAME_RE = re.compile(r'^\./data/baseballdatabank.*/core/([A-Za-z0-9_]+)\.csv$')

# helper: extract the name, or None if no match
file_name = lambda p: (m.group(1) if (m := FILE_NAME_RE.match(p)) else None)

# filter only Batting or People
is_batting_or_people = lambda p: file_name(p) in {"Batting", "People"}

result = [file_name(p) for p in files if is_batting_or_people(p)]
print(result)

['Batting', 'People']

#### Step 3 - Use a comprehension to read in all files

**Note:** The data is small (< 10mb total) so it is safe to read all at once.

In [76]:
dfs = {file_name(p):pl.read_csv(p) for p in files if is_batting_or_people(p)}
dfs['Batting'].head()

shape: (5, 22)
┌───────────┬────────┬───────┬────────┬───┬──────┬──────┬──────┬──────┐
│ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ HBP  ┆ SH   ┆ SF   ┆ GIDP │
│ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ str  ┆ str  ┆ str  ┆ i64  │
╞═══════════╪════════╪═══════╪════════╪═══╪══════╪══════╪══════╪══════╡
│ abercda01 ┆ 1871   ┆ 1     ┆ TRO    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ addybo01  ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ allisar01 ┆ 1871   ┆ 1     ┆ CL1    ┆ … ┆ null ┆ null ┆ null ┆ 1    │
│ allisdo01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
│ ansonca01 ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ null ┆ null ┆ null ┆ 0    │
└───────────┴────────┴───────┴────────┴───┴──────┴──────┴──────┴──────┘

In [79]:
dfs['People'].head()

shape: (5, 24)
┌───────────┬───────────┬────────────┬──────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ playerID  ┆ birthYear ┆ birthMonth ┆ birthDay ┆ … ┆ debut     ┆ finalGame ┆ retroID  ┆ bbrefID   │
│ ---       ┆ ---       ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ i64       ┆ i64        ┆ i64      ┆   ┆ str       ┆ str       ┆ str      ┆ str       │
╞═══════════╪═══════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ aardsda01 ┆ 1981      ┆ 12         ┆ 27       ┆ … ┆ 2004-04-0 ┆ 2015-08-2 ┆ aardd001 ┆ aardsda01 │
│           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
│ aaronha01 ┆ 1934      ┆ 2          ┆ 5        ┆ … ┆ 1954-04-1 ┆ 1976-10-0 ┆ aaroh101 ┆ aaronha01 │
│           ┆           ┆            ┆          ┆   ┆ 3         ┆ 3         ┆          ┆           │
│ aaronto01 ┆ 1939      ┆ 8          ┆ 5        ┆ … ┆ 1962-04-1 ┆ 1971-09-2 ┆ aarot101 ┆ aaronto01 │
│           ┆           ┆            ┆          ┆   ┆ 0         ┆ 6         ┆          ┆           │
│ aasedo01  ┆ 1954      ┆ 9          ┆ 8        ┆ … ┆ 1977-07-2 ┆ 1990-10-0 ┆ aased001 ┆ aasedo01  │
│           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
│ abadan01  ┆ 1972      ┆ 8          ┆ 25       ┆ … ┆ 2001-09-1 ┆ 2006-04-1 ┆ abada001 ┆ abadan01  │
│           ┆           ┆            ┆          ┆   ┆ 0         ┆ 3         ┆          ┆           │
└───────────┴───────────┴────────────┴──────────┴───┴───────────┴───────────┴──────────┴───────────┘

#### Step 4 - Preprocess each file.

In [80]:
# Filter, select, and aggregate hits for 2010.
(hits_in_2010_raw := 
 dfs['Batting']
.select(['yearID', 'playerID', 'H'])
.filter(pl.col('yearID') == 2010)
.group_by('playerID')
.agg(pl.col('H').mean().alias('Total Hits'))
).head()

shape: (5, 2)
┌───────────┬────────────┐
│ playerID  ┆ Total Hits │
│ ---       ┆ ---        │
│ str       ┆ f64        │
╞═══════════╪════════════╡
│ smithjo06 ┆ 0.0        │
│ markani01 ┆ 187.0      │
│ cabreev01 ┆ 44.0       │
│ weaveje02 ┆ 2.0        │
│ fisheca01 ┆ 0.0        │
└───────────┴────────────┘

In [81]:
# Grab the first and last names from People.

(player_names := 
 dfs['People']
 .select(['playerID', 'nameFirst', 'nameLast'])
).head(2)

shape: (2, 3)
┌───────────┬───────────┬──────────┐
│ playerID  ┆ nameFirst ┆ nameLast │
│ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪══════════╡
│ aardsda01 ┆ David     ┆ Aardsma  │
│ aaronha01 ┆ Hank      ┆ Aaron    │
└───────────┴───────────┴──────────┘

#### Step 4 -- Join the tables

In [82]:
(hits_in_2010 := 
 hits_in_2010_raw 
 .join(player_names, on='playerID', how='left')
 .drop('playerID')
).head()

shape: (5, 3)
┌────────────┬───────────┬──────────┐
│ Total Hits ┆ nameFirst ┆ nameLast │
│ ---        ┆ ---       ┆ ---      │
│ f64        ┆ str       ┆ str      │
╞════════════╪═══════════╪══════════╡
│ 0.0        ┆ Jordan    ┆ Smith    │
│ 187.0      ┆ Nick      ┆ Markakis │
│ 44.0       ┆ Everth    ┆ Cabrera  │
│ 2.0        ┆ Jered     ┆ Weaver   │
│ 0.0        ┆ Carlos    ┆ Fisher   │
└────────────┴───────────┴──────────┘

## <font color="red"> Exercise 3.2 </font>

We want to get the total hits allowed for all pitchers during the 2000-2010 seasons.  Use `glob` and a `dict` to collect this information into a table that includes the players first and last names.

In [101]:
# Your code here
import re

# normalize paths to forward slashes
files = [p.replace('\\', '/') for p in files]

FILE_NAME_RE = re.compile(r'^\./data/baseballdatabank.*/core/([A-Za-z0-9_]+)\.csv$')

# helper: extract the name, or None if no match
file_name = lambda p: (m.group(1) if (m := FILE_NAME_RE.match(p)) else None)

# filter only Batting or People
is_pitching_or_people = lambda p: file_name(p) in {"Pitching", "People"}

result = [file_name(p) for p in files if is_pitching_or_people(p)]
print(result)

['People', 'Pitching']

In [102]:
dfs = {file_name(p):pl.read_csv(p) for p in files if is_pitching_or_people(p)}
dfs['Pitching'].head()

shape: (5, 30)
┌───────────┬────────┬───────┬────────┬───┬─────┬──────┬──────┬──────┐
│ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ R   ┆ SH   ┆ SF   ┆ GIDP │
│ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---  │
│ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64 ┆ str  ┆ str  ┆ str  │
╞═══════════╪════════╪═══════╪════════╪═══╪═════╪══════╪══════╪══════╡
│ bechtge01 ┆ 1871   ┆ 1     ┆ PH1    ┆ … ┆ 42  ┆ null ┆ null ┆ null │
│ brainas01 ┆ 1871   ┆ 1     ┆ WS3    ┆ … ┆ 292 ┆ null ┆ null ┆ null │
│ fergubo01 ┆ 1871   ┆ 1     ┆ NY2    ┆ … ┆ 9   ┆ null ┆ null ┆ null │
│ fishech01 ┆ 1871   ┆ 1     ┆ RC1    ┆ … ┆ 257 ┆ null ┆ null ┆ null │
│ fleetfr01 ┆ 1871   ┆ 1     ┆ NY2    ┆ … ┆ 21  ┆ null ┆ null ┆ null │
└───────────┴────────┴───────┴────────┴───┴─────┴──────┴──────┴──────┘

In [92]:
dfs['People'].head()

shape: (5, 24)
┌───────────┬───────────┬────────────┬──────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ playerID  ┆ birthYear ┆ birthMonth ┆ birthDay ┆ … ┆ debut     ┆ finalGame ┆ retroID  ┆ bbrefID   │
│ ---       ┆ ---       ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ i64       ┆ i64        ┆ i64      ┆   ┆ str       ┆ str       ┆ str      ┆ str       │
╞═══════════╪═══════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ aardsda01 ┆ 1981      ┆ 12         ┆ 27       ┆ … ┆ 2004-04-0 ┆ 2015-08-2 ┆ aardd001 ┆ aardsda01 │
│           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
│ aaronha01 ┆ 1934      ┆ 2          ┆ 5        ┆ … ┆ 1954-04-1 ┆ 1976-10-0 ┆ aaroh101 ┆ aaronha01 │
│           ┆           ┆            ┆          ┆   ┆ 3         ┆ 3         ┆          ┆           │
│ aaronto01 ┆ 1939      ┆ 8          ┆ 5        ┆ … ┆ 1962-04-1 ┆ 1971-09-2 ┆ aarot101 ┆ aaronto01 │
│           ┆           ┆            ┆          ┆   ┆ 0         ┆ 6         ┆          ┆           │
│ aasedo01  ┆ 1954      ┆ 9          ┆ 8        ┆ … ┆ 1977-07-2 ┆ 1990-10-0 ┆ aased001 ┆ aasedo01  │
│           ┆           ┆            ┆          ┆   ┆ 6         ┆ 3         ┆          ┆           │
│ abadan01  ┆ 1972      ┆ 8          ┆ 25       ┆ … ┆ 2001-09-1 ┆ 2006-04-1 ┆ abada001 ┆ abadan01  │
│           ┆           ┆            ┆          ┆   ┆ 0         ┆ 3         ┆          ┆           │
└───────────┴───────────┴────────────┴──────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [103]:
(player_namess := 
 dfs['People']
 .select(['playerID', 'nameFirst', 'nameLast'])
).head(2)

shape: (2, 3)
┌───────────┬───────────┬──────────┐
│ playerID  ┆ nameFirst ┆ nameLast │
│ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪══════════╡
│ aardsda01 ┆ David     ┆ Aardsma  │
│ aaronha01 ┆ Hank      ┆ Aaron    │
└───────────┴───────────┴──────────┘

In [104]:
(hits_in_2010s := 
 dfs['Pitching']
.select(['yearID', 'playerID', 'H'])
.filter((pl.col('yearID') >= 2010) & (pl.col('yearID') <= 2020))
.group_by('playerID')
.agg(pl.col('H').mean().alias('Total Hits'))
).head()

shape: (5, 2)
┌───────────┬────────────┐
│ playerID  ┆ Total Hits │
│ ---       ┆ ---        │
│ str       ┆ f64        │
╞═══════════╪════════════╡
│ jimened01 ┆ 12.0       │
│ sanchan01 ┆ 136.166667 │
│ archech01 ┆ 125.222222 │
│ slanida01 ┆ 0.0        │
│ cedenxa01 ┆ 14.583333  │
└───────────┴────────────┘

In [105]:
(hits_in_teens := 
 hits_in_2010s
 .join(player_namess, on='playerID', how='left')
 .drop('playerID')
 .sort("Total Hits", descending=True)
).head()

shape: (5, 3)
┌────────────┬───────────┬──────────┐
│ Total Hits ┆ nameFirst ┆ nameLast │
│ ---        ┆ ---       ┆ ---      │
│ f64        ┆ str       ┆ str      │
╞════════════╪═══════════╪══════════╡
│ 221.5      ┆ Mark      ┆ Buehrle  │
│ 192.6      ┆ Hiroki    ┆ Kuroda   │
│ 190.363636 ┆ Rick      ┆ Porcello │
│ 189.666667 ┆ Carl      ┆ Pavano   │
│ 189.25     ┆ R. A.     ┆ Dickey   │
└────────────┴───────────┴──────────┘